### ISSUE TITLE
Questions on how to integrate in my plugin structure

### ISSUE THREAD

**Issue by araeubig** [YahnisElsts/admin-notices#6]
Dear Yahnis

i try to integrate the "admin-notices" in my plugin structure. But actually i have no idea how to do thi sthe right way. Since some years i'am using the clear structured boilerplate from Devin Winson [(https://github.com/DevinVinson/WordPress-Plugin-Boilerplate](url) and today i couldn't solve it. Would and could you give me a hint? It would be very helpful.

I understand that the integration should be made "on top" of all but based on the clear class structure from Devin i did not find the right point.

Regards André

**Comment by YahnisElsts** [comment]
Could you elaborate on what you mean by "integration"? The readme already covers installation and basic usage; I'm not sure what else is left. 

If you're asking where to put the actual library file(s), the boilerplate you mentioned suggests [three options](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate?tab=readme-ov-file#includes). I can't speak for Devin Winson, but since `admin-notices` is used in the admin dashboard, it sounds like it would go in `plugin-name/admin`. Or you could install it with Composer, which would automatically put it in a `vendor` subdirectory.

**Comment by araeubig** [comment]
In my plugin i use an /includes/libraries/ folder and there i put in the admin-notices folder. This is not a problem. My problem is to "load/integrate": require '/path/to/admin-notices/AdminNotice.php';

I try to develop my plugin completely without composer, therefore i couldn't install with it. Perhaps you know the "right" way to do it with the boilerplate. If i link the AdminNotice.php in [https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/blob/master/plugin-name/includes/class-plugin-name.php](url) i couldn't call it in my plugin admin files.

**Comment by YahnisElsts** [comment]
Unfortunately, I haven't used that boilerplate myself, and I don't know what the "right" way is in that context.

Looking at the file you mentioned, the `load_dependencies` method might be the intended place to put a `require` statement that loads a library. Then you just need to remember to add `use \YeEasyAdminNotices\V1\AdminNotice;` to the top of any file that actually uses it.

**Comment by araeubig** [comment]
Thanks for your help and advice: I forgot "use \YeEasyAdminNotices\V1\AdminNotice;". Now i will try again.

**Comment by araeubig** [comment]
Thanks for your help: It works perfect.

**Comment by YahnisElsts** [comment]
I'm glad it works! I'll close this now.

**Comment by gerardreches** [comment]
@araeubig You could also simply require it in you plugin's main file generated by WPPB. There's no need to do it within the classes.
